force-app/main/default/objects/Profile_Grouping__mdt/Profile_Grouping__mdt.object-meta.xml
<CustomObject>
    <label>Profile Grouping</label>
    <pluralLabel>Profile Groupings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Profile_Grouping__mdt/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Admin</fullName>
                <default>true</default>
                <label>Admin</label>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProfileCategorySingleton.cls
public with sharing class ProfileCategorySingleton {

    private static ProfileCategorySingleton instance = null;
    public String profileCategory {get; private set;}

    private ProfileCategorySingleton() {
        getProfileCategory();
    }

    private void getProfileCategory(){
        String userProfileName = [Select Name from Profile where Id =:UserInfo.getProfileId()].Name;
        for(Profile_Grouping__mdt pg :Profile_Grouping__mdt.getAll().values()){
            if(pg.MasterLabel == userProfileName){
                this.profileCategory = pg.Category__c;
                break;
            }
        }
    }

    public static ProfileCategorySingleton getInstance(){
        if(instance == null) instance = new ProfileCategorySingleton();
        return instance;
    }
}