force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SimpleLogger.cls
public virtual class SimpleLogger {

    protected String cause;
    protected String message;
    protected String stackTrace;
    protected String type;
    protected String lineNumber;

    public SimpleLogger() {}
    public SimpleLogger(String message){
        this.message = message;
    }

    public void setMessage(String message){
        this.message = message;
    }
    public void setStackTrace(String stackTrace){
        this.stackTrace = stackTrace;
    }
    public void setType(String type){
        this.type = type;
    }
    public void setCause(String cause){
        this.cause = cause;
    }
    public void setLineNumber(String lineNumber){
        this.lineNumber = lineNumber;
    }

    public virtual Logger__c commitLogger(){
        Logger__c log = new Logger__c();
        log.Message__c = message;
        log.Stack_Trace__c = stackTrace;
        log.Type__c = type;
        log.Line_Number__c = lineNumber;
        log.Cause__c = cause;
        insert log;
        return log;
    }
}