force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QueueableClass.cls
public with sharing class QueueableClass implements Queueable, Finalizer, Database.AllowsCallouts {

    private Integer numberOfErrors = 0;

    public QueueableClass(){}

    public QueueableClass(Integer numberOfErrors){
        this.numberOfErrors = numberOfErrors;
    }

    public void execute(System.QueueableContext qc){
        List<Task> tskList = new List<Task>();
        for(Account acct :[Select Id, Name from Account]){
            Task tsk = new Task(Subject=acct.Name);
            tskList.add(tsk);
        }

        List<Database.SaveResult> dbSaveList = Database.insert(tskList, false);
        for(Database.SaveResult sr :dbSaveList){
            if(sr.isSuccess()){
                system.debug('Successfully inserted record');
            }else{
                this.numberOfErrors++;
            }
        }

        QueueableClass q = new QueueableClass(numberOfErrors);
        system.attachFinalizer(q);
    }


    public void execute(FinalizerContext ctx){
        if(numberOfErrors > 0){
            Logger__c log = new Logger__c();
            log.Cause__c = 'QueueableClass '+ctx.getAsyncApexJobId();
            log.Message__c = numberOfErrors+ ' records had errors';
            insert log;
        }
    }
}