force-app/main/default/objects/Logger__c/Logger__c.object-meta.xml
<CustomObject>
    <label>Logger</label>
    <nameField>
        <displayFormat>Log-{00000}</displayFormat>
        <label>Logger Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Loggers</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Logger__c/fields/Cause__c.field-meta.xml
<CustomField>
    <fullName>Cause__c</fullName>
    <label>Cause</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Logger__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdatedLogger.cls
public class UpdatedLogger extends SimpleLogger implements LoggerInterface {


    public UpdatedLogger(String message, String stackTrace){
        super(message);
        this.stackTrace = stackTrace;
    }


    public override Logger__c commitLogger(){
        System.debug('This method has been overridden');
        Logger__c log = new Logger__c();
        log.Message__c = message;
        log.Stack_Trace__c = stackTrace;
        log.Type__c = type;
        log.Line_Number__c = lineNumber;
        log.Cause__c = cause;
        insert log;
        return log;
    }

    public void debugLogger(Logger__c log){
        System.debug(log);
    }

    public void newMethod(){
        System.debug('Only available from the updatedlogger');
    }

}